flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:DDCSF/repa
    commit: e3568d7a1213c208dba30c6acf8f12d84ef307e2
  subdirs:
  - repa
- location:
    git: git@github.com:ekmett/linear
    commit: 8da21dc72714441cb34d6eabd6c224819787365c
setup-info:
  ghc:
    linux64:
      8.0.0.20160421:
        url: https://downloads.haskell.org/~ghc/8.0.1-rc4/ghc-8.0.0.20160421-x86_64-unknown-linux.tar.xz
    macosx:
      8.0.0.20160421:
        url: https://downloads.haskell.org/~ghc/8.0.1-rc4/ghc-8.0.0.20160421-x86_64-apple-darwin.tar.xz
extra-deps:
- HUnit-1.3.1.1
- JuicyPixels-3.2.7
- QuickCheck-2.8.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-0.11.1.4
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- attoparsec-0.13.0.2
- base-orphans-0.5.4
- bifunctors-5.3
- bytes-0.15.2
- cereal-0.5.1.0
- cmdargs-0.10.14
- comonad-5
- conduit-1.2.6.4
- contravariant-1.4
- deepseq-generics-0.2.0.0
- distributive-0.5.0.2
- dlist-0.7.1.2
- enclosed-exceptions-1.0.1.1
- exceptions-0.8.2.1
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- free-4.12.4
- hashable-1.2.4.0
- heap-1.0.3
- hostname-1.0
- kan-extensions-5.0.1
- kdt-0.2.4
- lens-4.14
- lifted-base-0.2.3.6
- mmorph-1.0.6
- monad-control-1.0.1.0
- mtl-2.2.1
- old-locale-1.0.0.7
- parallel-3.2.1.0
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-posix-0.95.2
- resourcet-1.1.7.3
- scientific-0.3.4.6
- semigroupoids-5.0.1
- semigroups-0.18.1
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.4
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- text-1.2.2.1
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- void-0.7.1
- xml-1.3.14
- yaml-0.8.17.1
- zlib-0.6.1.1
compiler-check: match-exact
resolver: ghc-8.0.0.20160421
